services:
  node-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ai-interview-backend
    ports:
      - "4000:4000"
    env_file:
      - ../.env
    restart: unless-stopped
